# ==============================================================================
# Script 02: Data Ingestion and Structural Profiling
# Project: Week 3 - Statistical Analysis and Predictive Modeling Using R
# ==============================================================================

if (!exists("GLOBAL_SEED")) source("R/01_setup.R")

raw_data_path <- "data/raw/superstore_raw.csv"

if (!file.exists(raw_data_path)) {
  stop("FATAL ERROR: Raw data file not found at: ", raw_data_path)
}

# Import raw transaction records
superstore_raw <- readr::read_csv(
  raw_data_path,
  col_types = cols(.default = col_character()),
  show_col_types = FALSE
)

n_rows <- nrow(superstore_raw)
n_cols <- ncol(superstore_raw)

cat(sprintf(">>> [02_import_data.R] Ingested raw dataset: %d rows x %d columns\n", n_rows, n_cols))

# Construct comprehensive dataset overview manifest
var_roles <- c(
  "Row ID"        = "Identifier",
  "Order ID"      = "Identifier / Grouping",
  "Order Date"    = "Temporal Feature",
  "Ship Date"     = "Temporal Feature",
  "Ship Mode"     = "Categorical Predictor",
  "Customer ID"   = "Identifier",
  "Customer Name" = "Metadata",
  "Segment"       = "Categorical Predictor",
  "Country"       = "Constant Metadata",
  "City"          = "Geographic Granularity",
  "State"         = "Geographic Predictor",
  "Postal Code"   = "Geographic Code",
  "Region"        = "Categorical Predictor",
  "Product ID"    = "Identifier",
  "Category"      = "Categorical Predictor",
  "Sub-Category"  = "Categorical Predictor",
  "Product Name"  = "Metadata",
  "Sales"         = "Continuous Predictor / Auxiliary",
  "Quantity"      = "Continuous Predictor",
  "Discount"      = "Continuous Predictor",
  "Profit"        = "PRIMARY REGRESSION TARGET"
)

var_descriptions <- c(
  "Row ID"        = "Unique chronological database row integer",
  "Order ID"      = "Unique transaction order identifier (multi-item line grouping)",
  "Order Date"    = "Date transaction was placed by customer (DD-MM-YYYY)",
  "Ship Date"     = "Date merchandise was dispatched from warehouse",
  "Ship Mode"     = "Logistics shipping class (Standard, Second, First, Same Day)",
  "Customer ID"   = "Unique client identifier code",
  "Customer Name" = "Full name of purchasing commercial customer",
  "Segment"       = "Market client segment (Consumer, Corporate, Home Office)",
  "Country"       = "Country of transaction (United States)",
  "City"          = "Destination city across 531 municipalities",
  "State"         = "Destination US State across 49 states",
  "Postal Code"   = "5-digit US postal delivery code",
  "Region"        = "Commercial macro-region (West, East, Central, South)",
  "Product ID"    = "Unique stock keeping unit (SKU) identifier",
  "Category"      = "Broad product division (Technology, Office Supplies, Furniture)",
  "Sub-Category"  = "Specific product department (17 distinct classifications)",
  "Product Name"  = "Commercial trade brand and description of merchandise",
  "Sales"         = "Gross monetary revenue generated by line item in USD",
  "Quantity"      = "Total number of physical units purchased (1 to 14)",
  "Discount"      = "Promotional discount rate applied (0.00 to 0.80)",
  "Profit"        = "Net commercial profit or loss in USD (Regression Target)"
)

dataset_overview <- tibble(
  Variable = names(superstore_raw),
  Storage_Type = sapply(superstore_raw, class),
  Description = var_descriptions[names(superstore_raw)],
  Missing_Count = sapply(superstore_raw, function(x) sum(is.na(x))),
  Missing_Pct = sprintf("%.2f%%", sapply(superstore_raw, function(x) mean(is.na(x))) * 100),
  Unique_Values = sapply(superstore_raw, function(x) length(unique(x))),
  Modeling_Role = var_roles[names(superstore_raw)]
)

readr::write_csv(dataset_overview, "outputs/tables/dataset_overview.csv")

cat(">>> [02_import_data.R] Dataset overview manifest written to outputs/tables/dataset_overview.csv\n")
